### ISSUE TITLE
Error retrieving the state of entity

### ISSUE THREAD

**Issue by Chicob13** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#2]
This is the error message in the Octoprint logs.

2021-05-18 11:35:32,308 - octoprint.plugins.psucontrol_homeassistant - ERROR - Exception while making API call
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_homeassistant/__init__.py", line 67, in send
    response = requests.get(url, headers=headers, verify=verify_certificate)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'IP ADDRESS:8123/api/states/ENTITY.ID'

**Comment by edekeijzer** [comment]
Did you include the correct protocol? Your IP address should be prefixed with either http:// or https://

**Comment by Chicob13** [comment]
ah, figured it out, it is http://IP ADDRESS:8123 and not http://IP ADDRESS:8123/ that's why the http way wasn't working for me. TY very much, I will close the issue

**Comment by edekeijzer** [comment]
Good to know, I'll build in some check to strip off the path after the address as I could imagine anybody copying the entire URL from their browser.
