### ISSUE TITLE
Switch turn of by Printer Starts

### ISSUE THREAD

**Issue by GG-Style** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#9]
2022-02-25 20:53:30,289 - octoprint.plugins.psucontrol - INFO - Switching PSU On
2022-02-25 20:53:39,804 - octoprint.plugins.psucontrol - INFO - Switching PSU Off
2022-02-25 20:53:40,268 - octoprint.plugin - ERROR - Error while calling plugin homeassistant
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_homeassistant/__init__.py", line 1037, in on_event
    self._generate_psu_state(payload["isPSUOn"])
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_homeassistant/__init__.py", line 639, in _generate_psu_state
    allow_queueing=True,
TypeError: 'NoneType' object is not callable

**Comment by edekeijzer** [comment]
The errors you show are from a different plugin. I am not sure why it switches on and then off after some seconds, did you set both sensing and switching plugins correctly in PSU Control?
